### ISSUE TITLE
Error when running "python multiStonk.py"

### ISSUE THREAD

**Issue by whrit** [steveman1123/multiStonk#4]
2023-07-31 10:03:43.777417Traceback (most recent call last):
  File "/home/bw/Projects/stonkApp/multiStonk/multiStonk.py", line 997, in <module>
    main(verbose=False) #start running the program
  File "/home/bw/Projects/stonkApp/multiStonk/multiStonk.py", line 190, in main
    check2sells(pos)
  File "/home/bw/Projects/stonkApp/multiStonk/multiStonk.py", line 561, in check2sells
    gs = eval(f"{algo}.goodSells(symbList,verbose=False)")
  File "<string>", line 1, in <module>
  File "/home/bw/Projects/stonkApp/multiStonk/./algos/divs.py", line 67, in goodSells
    symbList = [e for e in symbList if e in posList] #make sure they're the ones in the posList only
  File "/home/bw/Projects/stonkApp/multiStonk/./algos/divs.py", line 67, in <listcomp>
    symbList = [e for e in symbList if e in posList] #make sure they're the ones in the posList only
TypeError: unhashable type: 'dict'

**Comment by steveman1123** [comment]
Can you please give steps to reproduce this problem? As well as the contents (or structure at least) of the posList file? It seems like you may have bad data in the posList dict

**Comment by whrit** [comment]
The problem occurs when I run the script with "python multiStonk.py". I'll put the contents of the posList file below; I also receive that same exact error whenever I run the script....

"{
  "algos": {
    "dj": {},
    "fda": {},
    "fda3": {},
    "iped": {
      "ARDX": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 659.0,
        "shouldSell": false,
        "buyPrice": 3.836358118,
        "note": "2023-03-28, top"
      },
      "BDN": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 505.0,
        "shouldSell": false,
        "buyPrice": 4.995623762,
        "note": "2023-03-28, top"
      },
      "CNDT": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 722.0,
        "shouldSell": false,
        "buyPrice": 3.499168975,
        "note": "2023-04-10, tech"
      },
      "COMP": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 598.0,
        "shouldSell": false,
        "buyPrice": 4.248946488,
        "note": "2023-04-10, tech"
      },
      "GOTU": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 568.0,
        "shouldSell": false,
        "buyPrice": 4.436109155,
        "note": "2023-01-09, t-ana"
      },
      "GRAB": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 675.0,
        "shouldSell": false,
        "buyPrice": 3.745407407,
        "note": "2023-04-10, tech"
      },
      "GTE": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 365.0,
        "shouldSell": false,
        "buyPrice": 6.874547945,
        "note": "2023-04-12, oilgas"
      },
      "INTR": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 666.0,
        "shouldSell": false,
        "buyPrice": 3.786786787,
        "note": "2023-03-28, top"
      },
      "LYG": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 1107.0,
        "shouldSell": false,
        "buyPrice": 2.3,
        "note": "2023-03-28, top"
      },
      "NAT": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 596.0,
        "shouldSell": false,
        "buyPrice": 4.250302013,
        "note": "2023-03-28, top"
      },
      "NOK": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 641.0,
        "shouldSell": false,
        "buyPrice": 3.95,
        "note": "2023-04-10, tech"
      },
      "REI": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 1059.0,
        "shouldSell": false,
        "buyPrice": 2.401057602,
        "note": "2023-04-12, oilgas"
      },
      "RXT": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 1120.0,
        "shouldSell": false,
        "buyPrice": 2.27,
        "note": "2023-04-10, tech"
      },
      "SB": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 759.0,
        "shouldSell": false,
        "buyPrice": 3.3314361,
        "note": "2023-01-09, t-ana"
      },
      "STEM": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 379.0,
        "shouldSell": false,
        "buyPrice": 6.595540897,
        "note": "2023-04-10, tech"
      },
      "TELL": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 1569.0,
        "shouldSell": false,
        "buyPrice": 1.621166348,
        "note": "2023-04-12, oilgas"
      },
      "UGP": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 642.0,
        "shouldSell": false,
        "buyPrice": 3.94,
        "note": "2023-04-12, oilgas"
      },
      "VLD": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 1225.0,
        "shouldSell": false,
        "buyPrice": 2.08,
        "note": "2023-04-10, tech"
      }
    },
    "divs": {
      "CFG": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 317.0,
        "shouldSell": false,
        "buyPrice": 32.218107256,
        "note": "2023-08-16, 0.42, 0.013"
      },
      "CPLP": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 669.0,
        "shouldSell": false,
        "buyPrice": 15.497488789,
        "note": "2023-08-08, 0.15, 0.009"
      },
      "HFWA": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 550.0,
        "shouldSell": false,
        "buyPrice": 18.737218182,
        "note": "2023-08-16, 0.22, 0.012"
      },
      "WBS": {
        "lastTradeDate": "NA",
        "lastTradeType": "NA",
        "sharesHeld": 214.0,
        "shouldSell": false,
        "buyPrice": 47.335140187,
        "note": "2023-08-16, 0.4, 0.008"
      }
    }
  },
  "cash": {
    "dj": {
      "earned": 0,
      "invested": 0
    },
    "fda": {
      "earned": 0,
      "invested": 0
    },
    "fda3": {
      "earned": 0,
      "invested": 0
    },
    "iped": {
      "earned": 0,
      "invested": 45542.99999931899
    },
    "divs": {
      "earned": 0,
      "invested": 41016.150000111
    }
  }
}"

**Comment by steveman1123** [comment]
This issue should be resolved now in [this commit](https://github.com/steveman1123/multiStonk/commit/a60d8c72b53fd3929374d0284cfca0aff175d91d). It was due to some errors while processing data in the divs algo file.
